spring:
  application:
    name: ${APP_NAME:cnheri-admin}
  security:
    user:
      name: ${SECURITY_USER_NAME:admin}
      password: ${SECURITY_USER_PASSWORD:admin}
  zipkin:
    base-url: http://${ZIPKIN_SERVER_IP:localhost}:${ZIPKIN_SERVER_PORT:9411}
  sleuth:
    sampler:
      probability: 0.1
server:
  port: 8084

eureka:
  instance:
    health-check-url-path: /actuator/health
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://admin:admin@localhost:8761/eureka/,http://admin:admin@localhost:8861/eureka/,http://admin:admin@localhost:8961/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS