spring:
  application:
    name: ${APP_NAME:cnheri-eureka}
  security:
    user:
      name: ${SECURITY_USER_NAME:admin}
      password: ${SECURITY_USER_PASSWORD:admin}
  boot:
    admin:
      client:
        url: http://${SECURITY_USER_NAME:admin}:${SECURITY_USER_PASSWORD:admin}@${ADMIN_SERVER_IP:localhost}:${ADMIN_SERVER_PORT:8084}
  zipkin:
    base-url: http://${Zcd .//IPKIN_SERVER_IP:localhost}:${ZIPKIN_SERVER_PORT:9411}
  sleuth:
    sampler:
      probability: 0.1
server:
  port: 8761
eureka:
  instance:
    hostname: host
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://admin:admin@localhost:8761/eureka/,http://admin:admin@localhost:8861/eureka/,http://admin:admin@localhost:8961/eureka/}
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS