spring:
  application:
    name: cnheri-token-admin
  zipkin:
    base-url: http://47.105.64.181:9411
  sleuth:
    sampler:
      probability: 0.1
server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.105.64.181:8761/eureka/,http://121.37.187.157:8761/eureka/,http://121.37.185.48:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info