spring:
  application:
    name: cnheri-token-admin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.1
server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8861/eureka/,http://localhost:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info