spring:
  application:
    name: hello-spring-cloud-web-admin-ribbon
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  zipkin:
    base-url: http://localhost:9411
    #设置Sleuth的抽样收集概率
  sleuth:
    sampler:
      probability: 0.1

server:
  port: 8767

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/