spring:
  application:
    name: cnheri-token-config
  boot:
    admin:
      client:
        url: http://47.105.64.181:8084
  zipkin:
    base-url: http://47.105.64.181:9411
  sleuth:
    sampler:
      probability: 0.1
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/cnheri-token/cnheri-token-config
          search-paths: respo
          username: richardle1983
          password: Ljb@314159265

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.105.64.181:8761/eureka/,http://121.37.187.157:8761/eureka/,http://121.37.185.48:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info