# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: cnheri-token-config

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: rdc-snapshots # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the maven-settings.xml file
      - name: Build with Maven
        env:
          GITHUB_ACTOR: ${{ secrets.MAVEN_USER_NAME }}
          GITHUB_TOKEN: ${{ secrets.MAVEN_USER_PASSWORD }}
        run: |
          echo $GITHUB_ACTOR $GITHUB_TOKEN
          mvn clean deploy -DskipTests
